import type { Creature } from './types';

const MATERIAL = 'Résine teintée dans la masse, flocage doux au toucher';

/**
 * The catalogue. Order does not matter: lists are sorted by `number`.
 * Visual parameters (fur, detail, shape, seed) drive the 3D creature, the
 * pre-rendered still and the CSS fallback.
 */
export const creatures: Creature[] = [
  {
    slug: 'brume',
    number: 1,
    name: 'Brume',
    collection: 'nebuleuse',
    tagline: 'La première arrivée, légère comme un matin couvert.',
    story: [
      'Brume est apparue un soir sans lune, posée sur le rebord d’une fenêtre. Personne ne l’a vue arriver ; tout le monde l’a sentie.',
      'Sa petite mèche se soulève quand on passe à côté d’elle. On raconte qu’elle indique la direction d’où elle vient.',
    ],
    size: '6,5 cm',
    material: MATERIAL,
    seed: 11,
    fur: { base: '#D2C4F8', tip: '#9F8AE6', length: 0.13, density: 105, thickness: 0.6, droop: 0.35, flow: 0.35 },
    detail: { kind: 'tuft', amount: 0.9 },
    shape: { squash: 0.96, lumpiness: 0.05 },
    featured: true,
  },
  {
    slug: 'praline',
    number: 2,
    name: 'Praline',
    collection: 'sucrerie',
    tagline: 'Des taches tendres, comme du sucre qui fond.',
    story: [
      'Praline aime les endroits tièdes : le creux d’une main, un coin de radiateur, la poche d’un manteau.',
      'Ses taches ne sont jamais tout à fait au même endroit d’un jour sur l’autre. C’est du moins ce qu’affirment ceux qui la regardent longtemps.',
    ],
    size: '6 cm',
    material: MATERIAL,
    seed: 23,
    fur: { base: '#F8C9DB', tip: '#E58DB0', length: 0.11, density: 115, thickness: 0.55, droop: 0.3, flow: 0.3 },
    detail: { kind: 'spots', color: '#D9709B', amount: 0.55 },
    shape: { squash: 0.93, lumpiness: 0.06 },
    featured: true,
  },
  {
    slug: 'minuit',
    number: 3,
    name: 'Minuit',
    collection: 'nebuleuse',
    tagline: 'Une bande d’argent, comme une orbite qu’on aurait gardée.',
    story: [
      'Minuit ne se montre qu’à moitié. Le reste du temps, on ne voit que la bande argentée qui fait le tour de son pelage.',
      'Il est le plus silencieux de la collection. Même pour une créature sans bouche, c’est remarquable.',
    ],
    size: '7 cm',
    material: MATERIAL,
    seed: 37,
    fur: { base: '#4B4A9B', tip: '#2A2566', length: 0.12, density: 120, thickness: 0.55, droop: 0.3, flow: 0.4 },
    detail: { kind: 'sheen', color: '#DCDDF2', amount: 0.8 },
    shape: { squash: 0.95, lumpiness: 0.04 },
    featured: true,
  },
  {
    slug: 'pistache',
    number: 4,
    name: 'Pistache',
    collection: 'sucrerie',
    tagline: 'Une ceinture plus claire, douce comme une glace d’été.',
    story: [
      'Pistache est ronde, franche, un peu têtue. Elle roule toujours vers la lumière.',
      'La bande claire qui l’entoure serait la trace d’une très longue sieste au soleil d’une autre planète.',
    ],
    size: '6,5 cm',
    material: MATERIAL,
    seed: 41,
    fur: { base: '#C6EBD6', tip: '#8FCBAA', length: 0.1, density: 110, thickness: 0.6, droop: 0.25, flow: 0.25 },
    detail: { kind: 'band', color: '#DDF2E5', amount: 0.5 },
    shape: { squash: 0.9, lumpiness: 0.05 },
  },
  {
    slug: 'abricot',
    number: 5,
    name: 'Abricot',
    collection: 'aurore',
    tagline: 'Rien que de la chaleur, sans un seul détail de trop.',
    story: [
      'Abricot n’a ni tache, ni mèche, ni rayure. Il a décidé que la couleur suffisait.',
      'Posé sur une étagère, il donne l’impression qu’il est toujours cinq heures du soir, en septembre.',
    ],
    size: '6 cm',
    material: MATERIAL,
    seed: 53,
    fur: { base: '#FBD8B4', tip: '#F2A66E', length: 0.12, density: 100, thickness: 0.6, droop: 0.35, flow: 0.3 },
    detail: { kind: 'plain' },
    shape: { squash: 0.94, lumpiness: 0.07 },
    featured: true,
  },
  {
    slug: 'comete',
    number: 6,
    name: 'Comète',
    collection: 'nebuleuse',
    tagline: 'Parsemée d’éclats, comme un ciel très clair.',
    story: [
      'Comète est arrivée vite et n’a jamais vraiment ralenti. Ses poils sont piqués de minuscules éclats qui accrochent la lumière.',
      'La nuit, certains jurent qu’elle brille un peu. Nous n’avons jamais réussi à le prouver.',
    ],
    size: '5,5 cm',
    material: MATERIAL,
    seed: 67,
    fur: { base: '#BBD6F9', tip: '#6F9FE6', length: 0.1, density: 118, thickness: 0.55, droop: 0.25, flow: 0.45 },
    detail: { kind: 'speckle', color: '#FFFFFF', amount: 0.7 },
    shape: { squash: 0.97, lumpiness: 0.05 },
    isNew: true,
  },
  {
    slug: 'reglisse',
    number: 7,
    name: 'Réglisse',
    collection: 'aurore',
    tagline: 'Une couronne de mèches, portée sans y penser.',
    story: [
      'Réglisse est la plus sombre des créatures de l’aube : elle arrive juste avant, quand le ciel est encore violet.',
      'Sa couronne de petites mèches bouge au moindre souffle. Elle n’en tire aucune vanité.',
    ],
    size: '7 cm',
    material: MATERIAL,
    seed: 71,
    fur: { base: '#6A55B8', tip: '#3B2E85', length: 0.12, density: 112, thickness: 0.58, droop: 0.3, flow: 0.35 },
    detail: { kind: 'crown', color: '#8E78E4', amount: 0.85 },
    shape: { squash: 0.95, lumpiness: 0.05 },
  },
  {
    slug: 'chantilly',
    number: 8,
    name: 'Chantilly',
    collection: 'sucrerie',
    tagline: 'Une frange rose, comme un nuage au couchant.',
    story: [
      'Chantilly est la plus duveteuse de toutes. Sa frange rose traîne un peu, comme un ourlet trop long.',
      'Elle déteste les courants d’air et adore les étagères hautes, d’où elle peut tout observer.',
    ],
    size: '7,5 cm',
    material: MATERIAL,
    seed: 83,
    fur: { base: '#FFF1DD', tip: '#F3B8CC', length: 0.15, density: 100, thickness: 0.6, droop: 0.45, flow: 0.3 },
    detail: { kind: 'fringe', color: '#F3B8CC', amount: 0.9 },
    shape: { squash: 0.92, lumpiness: 0.06 },
    isNew: true,
  },
  {
    slug: 'lagune',
    number: 9,
    name: 'Lagune',
    collection: 'maree',
    tagline: 'Des rayures douces, comme l’eau quand le vent tombe.',
    story: [
      'Lagune a été trouvée dans une flaque tiède, un matin de grande marée. Elle n’était pas mouillée du tout.',
      'Ses rayures suivent la forme de son corps, comme les rides lentes d’une eau calme.',
    ],
    size: '6,5 cm',
    material: MATERIAL,
    seed: 97,
    fur: { base: '#A9DDE0', tip: '#5FAFB8', length: 0.1, density: 115, thickness: 0.55, droop: 0.25, flow: 0.4 },
    detail: { kind: 'stripes', color: '#E3F5F4', amount: 0.55 },
    shape: { squash: 0.93, lumpiness: 0.05 },
    isNew: true,
  },
  {
    slug: 'galet',
    number: 10,
    name: 'Galet',
    collection: 'maree',
    tagline: 'Gris tendre, moucheté, parfaitement tranquille.',
    story: [
      'Galet ressemble tant à une pierre polie qu’il a passé des années sur une plage sans que personne ne le remarque.',
      'Il est un peu plus plat que les autres. Il dit que c’est pour mieux tenir en équilibre.',
    ],
    size: '6 cm',
    material: MATERIAL,
    seed: 101,
    fur: { base: '#D9D4CC', tip: '#A69E92', length: 0.08, density: 128, thickness: 0.5, droop: 0.2, flow: 0.25 },
    detail: { kind: 'speckle', color: '#7E766B', amount: 0.55 },
    shape: { squash: 0.84, lumpiness: 0.08 },
  },
  {
    slug: 'ecume',
    number: 11,
    name: 'Écume',
    collection: 'maree',
    tagline: 'Blanche, bleutée, avec une mèche qui ne tient pas en place.',
    story: [
      'Écume change d’humeur avec la lumière : blanche le matin, presque bleue le soir.',
      'Sa mèche est la plus longue de tout le catalogue. Nous avons renoncé à la coiffer.',
    ],
    size: '7 cm',
    material: MATERIAL,
    seed: 113,
    fur: { base: '#F4F8FB', tip: '#BBD6F9', length: 0.14, density: 104, thickness: 0.6, droop: 0.4, flow: 0.45 },
    detail: { kind: 'tuft', amount: 1 },
    shape: { squash: 0.95, lumpiness: 0.06 },
    isNew: true,
  },
  {
    slug: 'mirabelle',
    number: 12,
    name: 'Mirabelle',
    collection: 'aurore',
    tagline: 'Dorée, tachetée, comme un fruit tombé dans l’herbe.',
    story: [
      'Mirabelle apparaît à la fin de l’été, quand les jours raccourcissent et que la lumière devient dorée.',
      'Ses taches ont la couleur du miel. Elle les porte avec un sérieux admirable.',
    ],
    size: '5,5 cm',
    material: MATERIAL,
    seed: 127,
    fur: { base: '#F9E3A3', tip: '#E9B85A', length: 0.1, density: 112, thickness: 0.58, droop: 0.3, flow: 0.3 },
    detail: { kind: 'spots', color: '#D99A3E', amount: 0.45 },
    shape: { squash: 0.95, lumpiness: 0.06 },
  },
  {
    slug: 'orage',
    number: 13,
    name: 'Orage',
    collection: 'nebuleuse',
    tagline: 'Des rayures sombres, un calme d’avant la pluie.',
    story: [
      'Orage est arrivé pendant une nuit électrique. Il en garde des rayures de nuages, bien rangées.',
      'Malgré son nom, c’est la créature la plus paisible de l’observatoire. Il aime surtout les jours de pluie.',
    ],
    size: '7 cm',
    material: MATERIAL,
    seed: 131,
    fur: { base: '#8C86C9', tip: '#4B4A9B', length: 0.11, density: 116, thickness: 0.56, droop: 0.3, flow: 0.4 },
    detail: { kind: 'stripes', color: '#3A3480', amount: 0.6 },
    shape: { squash: 0.94, lumpiness: 0.05 },
  },
  {
    slug: 'guimauve',
    number: 14,
    name: 'Guimauve',
    collection: 'sucrerie',
    tagline: 'La plus moelleuse. Presque trop.',
    story: [
      'Guimauve a une fourrure si longue qu’on hésite à dire où elle commence vraiment.',
      'Elle ne fait rien de particulier. Elle est là, et c’est déjà beaucoup.',
    ],
    size: '7,5 cm',
    material: MATERIAL,
    seed: 139,
    fur: { base: '#FFE4EC', tip: '#D2C4F8', length: 0.17, density: 96, thickness: 0.62, droop: 0.5, flow: 0.35 },
    detail: { kind: 'plain' },
    shape: { squash: 0.93, lumpiness: 0.07 },
  },
];

export const sortedCreatures = [...creatures].sort((a, b) => a.number - b.number);

export const creatureBySlug = (slug: string) => creatures.find((c) => c.slug === slug);

/** « N° 001 » */
export const formatNumber = (n: number) => `N° ${String(n).padStart(3, '0')}`;
